apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: transformers
  annotations:
    scenarios.ai.sap.com/description: "transformers"
    scenarios.ai.sap.com/name: "transformers"
    executables.ai.sap.com/description: "transformers"
    executables.ai.sap.com/name: "transformers"
  labels:
    scenarios.ai.sap.com/id: "transformers"
    ai.sap.com/version: "1.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.l
    spec: |
      predictor:
        imagePullSecrets:
          - name: felixdockersecrect
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kserve-container
          image: docker.io/bfwork/huggingcore-customgpu
          ports:
            - containerPort: 8080
              protocol: TCP